### PR TITLE
Fix countdown mobile

### LINKED ISSUE #27: Fix Countdown Clock Styling
image

Countdown clock is not reactive and not exactly centered.
- [x] update styling with flexbox to center timer
- [x] adjust styling to make design responsive to mobile views
- [x] use media queries if necessary

### PR DESCRIPTION
**Pull request by burturt**
Closes #27 
Updates countdown timer to use flexbox. 

<details>
<summary>Screenshots (I removed the lower sections below about for these pictures since they still need to be fixed):</summary>

Screen Shot 2022-10-25 at 11 28 18 PM

Screen Shot 2022-10-25 at 11 28 22 PM

Screen Shot 2022-10-25 at 11 28 28 PM

PNG image
</details>

### CODE REVIEW

**Review by bliutech — CHANGES_REQUESTED** [review]
image
Aspect ratio is not quite correct for mobile view. Could we maybe add media queries to fix this?

**Comment by burturt** [comment]
Do you mean like where the title/banner/time/countdown is placed in relation to each other on the landing screen?

**Comment by bliutech** [comment]
@burturt I think the size of the buttons is too small. It should be roughly the same size and thus the margin should be reduce with media queries on reduced page width.

**Comment by burturt** [comment]
https://user-images.githubusercontent.com/31748545/197959690-990356ac-196b-4e4a-b690-58ab2432b7dd.mp4

this is what I have now - any feedback?

**Comment by bliutech** [comment]
@burturt Does that follow the media query sizes for standard screens? If yes, then we are good. If you check the Chrome developer tools, there is a tool that shows the specific screen sizes for all standard devices that we need to account for.

**Comment by burturt** [comment]
The media queries I attached to the page occur at 1024px and 600px.

**Review by bliutech — APPROVED** [review]
This is good enough for me for now. I think we will check in with the marketing peeps to see if they have any comments or feedback on the page styling. But I'll merge for now.

**Pull request merged**
