### PR TITLE
Update about to new figma design

### LINKED ISSUE #29: Update Text Section
**Figma Design:**
image

**Current Site:**
image

Update the current site to conform to the Figma's design for the middle text section.
- [x] export SVGs from Figma
- [x] update text content
- [x] most likely use flexbox to allow for dynamic and accurate centering
- [x] ensure that it confirms on mobile views
- [x] add onhover animation for SVGs to make it pop :)

### PR DESCRIPTION
**Pull request by burturt**
Closes #29, replaces #30

Screen Shot 2022-10-25 at 12 44 51 AM
Screen Shot 2022-10-25 at 12 44 57 AM
On Hover:
Screen Shot 2022-10-25 at 12 45 00 AM

### CODE REVIEW

**Review by bliutech — CHANGES_REQUESTED** [review]
@burturt could you please rebase this branch to remove ```package-lock.json``` if you see from the ```README.md``` we are using yarn so I want to prevent unnecessary boat.

**Comment by burturt** [comment]
Fixed - my bad, I did not see that.

**Review by bliutech — APPROVED** [review]
Very impressed! Actually looks very smooth and perfect. LGTM. Thanks!

**Comment by burturt** [comment]
~~do you want me to run prettier on it before merging?~~ nvm you did it

**Comment by bliutech** [comment]
I gotchu 👌

**Pull request merged**
